// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbqp2uDqx_v-GG2BjLhKT7U5ZQ7ksY11E',
    appId: '1:882216689426:web:88e12b01f87ee006dc1dcb',
    messagingSenderId: '882216689426',
    projectId: 'food-app-6d6f4',
    authDomain: 'food-app-6d6f4.firebaseapp.com',
    storageBucket: 'food-app-6d6f4.appspot.com',
    measurementId: 'G-E9HPM1QE2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiyi8TjAwlSFqKRbyENS-6A_FmJoR8Rro',
    appId: '1:882216689426:android:2abc85592435a069dc1dcb',
    messagingSenderId: '882216689426',
    projectId: 'food-app-6d6f4',
    storageBucket: 'food-app-6d6f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsbw6I5HQA9NlWSUH-NUHREX6Y2mhz49I',
    appId: '1:882216689426:ios:d029ddad8359afc7dc1dcb',
    messagingSenderId: '882216689426',
    projectId: 'food-app-6d6f4',
    storageBucket: 'food-app-6d6f4.appspot.com',
    iosBundleId: 'com.foodwasted.foodWastedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsbw6I5HQA9NlWSUH-NUHREX6Y2mhz49I',
    appId: '1:882216689426:ios:d029ddad8359afc7dc1dcb',
    messagingSenderId: '882216689426',
    projectId: 'food-app-6d6f4',
    storageBucket: 'food-app-6d6f4.appspot.com',
    iosBundleId: 'com.foodwasted.foodWastedApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbqp2uDqx_v-GG2BjLhKT7U5ZQ7ksY11E',
    appId: '1:882216689426:web:2e34616c65544e87dc1dcb',
    messagingSenderId: '882216689426',
    projectId: 'food-app-6d6f4',
    authDomain: 'food-app-6d6f4.firebaseapp.com',
    storageBucket: 'food-app-6d6f4.appspot.com',
    measurementId: 'G-2V7SFEWNXX',
  );
}
